### ISSUE TITLE
libevent_pthreads is not included in the bitcoind binary

### ISSUE THREAD

**Issue by satoshiware** [satoshiware/bitcoin#5]
Compiling according to ./doc/build-unix.md, you get the following error when running bitcoind:
"error while loading shared libraries: libevent_pthreads-2.1.so.7: cannot open shared object file: No such file or directory"

Current workaround:
     #Install libevent library
      sudo apt-get -y install libevent-dev

**Comment by GrantBirki** [comment]
My specific error was:

```text
error while loading shared libraries: libevent_pthreads-2.1.so.7: cannot open shared object file: No such file or directory
```

This indeed fixed it for me: `sudo apt-get -y install libevent-dev`
